#!/bin/bash
./y.sh src/designtypes/Piston-Cylinder/ResultTableOptimize.js
./y.sh src/designtypes/Solid/ResultTableOptimize.js
./y.sh src/designtypes/Spring/Extension/ReportBase.js
./y.sh src/designtypes/Spring/Extension/Report1.js
./y.sh src/designtypes/Spring/Extension/Report3.js
./y.sh src/designtypes/Spring/Extension/ResultTableOptimize.js
./y.sh src/designtypes/Spring/Extension/Report2.js
./y.sh src/designtypes/Spring/Extension/Calculator.js
./y.sh src/designtypes/Spring/Compression/ReportBase.js
./y.sh src/designtypes/Spring/Compression/Report1.js
./y.sh src/designtypes/Spring/Compression/Report3.js
./y.sh src/designtypes/Spring/Compression/ResultTableOptimize.js
./y.sh src/designtypes/Spring/Compression/Report2.js
./y.sh src/designtypes/Spring/Compression/Calculator.js
./y.sh src/designtypes/Spring/Torsion/ReportBase.js
./y.sh src/designtypes/Spring/Torsion/Report1.js
./y.sh src/designtypes/Spring/Torsion/Report3.js
./y.sh src/designtypes/Spring/Torsion/ResultTableOptimize.js
./y.sh src/designtypes/Spring/Torsion/Report2.js
./y.sh src/designtypes/Spring/Torsion/Calculator.js
./y.sh src/designtypes/Spring/SymbolValueWireDia.js
./y.sh src/components/ConstraintsMaxRowDependentVariable.js
./y.sh src/components/FeasibilityIndicator.js
./y.sh src/components/ValueName.js
./y.sh src/components/MessageModal.js
./y.sh src/components/ConstraintsMinHeaderDependentVariable.js
./y.sh src/components/DesignTable.js
./y.sh src/components/SymbolValue.js
./y.sh src/components/SymbolName.js
./y.sh src/components/AlertsAccordion.js
./y.sh src/components/Alerts.js
./y.sh src/components/ConstraintsMaxHeaderIndependentVariable.js
./y.sh src/components/NameValueUnitsCalcInputTable.js
./y.sh src/components/ConstraintsMinRowIndependentVariable.js
./y.sh src/components/NameValueUnitsRowIndependentVariable.js
./y.sh src/components/ConstraintsMinHeaderIndependentVariable.js
./y.sh src/components/ConstraintsMinTable.js
./y.sh src/components/Spinner.js
./y.sh src/components/NameValueUnitsHeaderCalcInput.js
./y.sh src/components/ConstraintsMaxTable.js
./y.sh src/components/ConstraintsMaxRowIndependentVariable.js
./y.sh src/components/SignInPage.js
./y.sh src/components/SearchDocs.js
./y.sh src/components/FormControlTypeNumber.js
./y.sh src/components/ResultTable.js
./y.sh src/components/Value.js
./y.sh src/components/NameValueUnitsHeaderIndependentVariable.js
./y.sh src/components/Routes.js
./y.sh src/components/ConstraintsMinRowDependentVariable.js
./y.sh src/components/MainPage.js
./y.sh src/components/NameValueUnitsTable.js
./y.sh src/components/NameValueUnitsHeaderDependentVariable.js
./y.sh src/components/SymbolUnits.js
./y.sh src/components/NameValueUnitsRowDependentVariable.js
./y.sh src/components/ConstraintsMaxHeaderDependentVariable.js
./y.sh src/components/NameValueUnitsRowCalcInput.js
./y.sh src/components/SignInPageWidget.js
./y.sh src/components/ExecutePanel.js
./y.sh src/menus/File/FileSaveAs.js
./y.sh src/menus/File/FileDelete.js
./y.sh src/menus/File/FileImport.js
./y.sh src/menus/File/FileProperties.js
./y.sh src/menus/File/FilePreferences.js
./y.sh src/menus/File/FileExport.js
./y.sh src/menus/File/FileSave.js
./y.sh src/menus/File/FileRecent.js
./y.sh src/menus/File/FileOpen.js
./y.sh src/menus/Action/ActionSeek.js
./y.sh src/menus/Action/ActionExecute.js
./y.sh src/menus/Action/ActionSelectCatalog.js
./y.sh src/menus/Action/ActionSearch.js
./y.sh src/menus/Action/ActionSelectSize.js
./y.sh src/menus/Action/ActionTrade.js
./y.sh src/menus/View/ViewSymbolTable.js
./y.sh src/menus/View/ViewObjectiveValue.js
./y.sh src/menus/View/ViewSymbolTableOffsets.js
./y.sh src/menus/View/ViewCADModel.js
./y.sh src/menus/View/ViewSelect.js
./y.sh src/menus/View/ViewOffsets.js
./y.sh src/menus/Help/HelpIndex.js
./y.sh src/menus/Help/HelpAbout.js
./y.sh src/menus/Help/HelpTutorial.js
./y.sh src/menus/Help/HelpDemo.js
./y.sh src/menus/Help/HelpMotd.js
./y.sh src/menus/Session/SignIn.js
./y.sh src/menus/Session/SignOut.js
