export const initialSystemControls = {
    "ioopt": {value: 3, tooltip: "IO option. Influences detail of output in the user interface. Default = 3. Open browser console and increase this value to see more.  Decrease to see less."},
    "maxit": {value: 600, tooltip: "Iteration limit for Search. Default = 600. See on-line Help entry on Search"},
    "weapon": {value: 1, tooltip: "Reserved for future use"},
    "nmerit": {value: 1, tooltip: "Reserved for future use"},
    "fix_wt": {value: 1.5, tooltip: "Weight factor for contribution of fixed dependent variable violations to Objective Value. Default = 1.5."},
    "con_wt": {value: 1.0, tooltip: "Weight factor for constraint violations in calculation of Objective Value. Default = 1.0"},
    "zero_wt": {value: 10.0, tooltip: "Reserved for future use"},
    "viol_wt": {value: 1.0, tooltip: "Weight factor for sum of constraint violations relative to the Merit Function in calculation of Objective Value. Default = 1.0"},
    "mfn_wt": {value: 0.005, tooltip: "Weight factor for Merit Function. Influences contribution of the Merit Function relative to constraint violations in calculation of Objective Value. Influences degree of constraint violation in outcome of Seek. Default = 0.005."},
    "objmin": {value: 0.00001, tooltip: "Convergence criterion for Search. Default = 0.00001. See on-line Help entry on Search"},
    "del": {value: 1.0, tooltip: "Starting value of the local exploration size. Default = 1.0. See on-line Help entry on Search"},
    "delmin": {value: 0.0001, tooltip: "Convergence criterion for Search. Default = 0.0001. See on-line Help entry on Search"},
    "tol": {value: 0.0001, tooltip: "Pattern Search's pattern break and step cut criterion. Default = 0.0001. See on-line Help entry on Search"},
    "smallnum": {value: 1.0e-07, tooltip: "Used as test to avoid division by zero. Used to detect unreasonably small values. Default = 1.0e-07"},
    "show_units": {value: 1, tooltip: "Setting value to 0 suppresses the units column in Advanced View. Default = 1. Use to reduce the need for horizontal scrolling on small displays."},
    "show_violations": {value: 1, tooltip: "Setting value to 0 suppresses the constraint violations column in Advanced View. Default = 1. Setting value to 2 shows degree of constraint satisfaction as a negative number."},
    "enable_auto_fix": {value: 1, tooltip: "Automatically applies Fixed status to independent variables whose values are changed by user input. Default = 1. Set value to 0 to disable this behavior."},
    "enable_auto_search": {value: 1, tooltip: "When enabled, the Auto Search feature automatically triggers a Search operation after user input. Default = 1. Set value to 0 to disable this behavior."}
};