export const initialSystemControls = {
        "ioopt": { value: 3 },
        "maxit": { value: 100 },
        "weapon": { value: 1 },
        "nmerit": { value: 1 },
        "fix_wt": { value: 1.5 },
        "con_wt": { value: 1.0 },
        "zero_wt": { value: 10.0 },
        "viol_wt": { value: 1.0 },
        "mfn_wt": { value: 0.01 },
        "objmin": { value: 0.00005 },
        "del": { value: 1.0 },
        "delmin": { value: 0.0001 },
        "tol": { value: 0.0001 },
        "smallnum": { value: 1.0e-07 },
        "show_units": { value: 1 },
        "show_violations": { value: 1 },
        "enable_auto_fix": { value: 1 }
    };
