// Independent Variables
export const OD_Free = 0;
export const Wire_Dia = 1;
export const L_Free = 2;
export const Coils_T = 3;
export const Force_1 = 4;
export const Force_2 = 5;
export const Spring_Type = 6;
export const Material_Type = 7;
export const ASTM_Fed_Spec = 8;
export const End_Type = 9;
export const Catalog_Number = 10;
export const Process = 11;
export const Material_File = 12;
export const Dialog_Switch = 13;
export const Prop_Calc_Method = 14;
export const End_Calc_Method = 15;
export const Life_Category = 16;
export const Material_Index = 17;
export const End_Type_Index = 18;
export const Inactive_Coils = 19;
export const Add_Coils_Solid = 20;
export const Density = 21;
export const Torsion_Modulus = 22;
export const Hot_Factor_Kh = 23;
export const PC_Tensile_Endur = 24;
export const PC_Tensile_Stat = 25;
export const unused = 26;
export const tbase010 = 27; // Hidden
export const tbase400 = 28; // Hidden
export const const_term = 29; // Hidden
export const slope_term = 30; // Hidden
export const tensile_010 = 31; // Hidden

// Dependent Variables
export const Mean_Dia = 0;
export const Coils_A = 1;
export const Rate = 2;
export const Deflect_1 = 3;
export const Deflect_2 = 4;
export const L_1 = 5;
export const L_2 = 6;
export const L_Stroke = 7;
export const L_Solid = 8;
export const Slenderness = 9;
export const ID_Free = 10;
export const Weight = 11;
export const Spring_Index = 12;
export const Force_Solid = 13;
export const Stress_1 = 14;
export const Stress_2 = 15;
export const Stress_Solid = 16;
export const FactorSafety_2 = 17;
export const FactorSafety_Solid = 18;
export const FS_CycleLife = 19;
export const Cycle_Life = 20;
export const PC_Avail_Deflect = 21;
export const Tensile = 22;
export const Stress_Lim_Endur = 23;
export const Stress_Lim_Stat = 24;
