// Independent Variables
const OD_Free = 0;
const Wire_Dia = 1;
const L_Free = 2;
const Coils_T = 3;
const Force_1 = 4;
const Force_2 = 5;
//const Spring_Type = 6;
//const Material_Type = 7;
//const ASTM_Fed_Spec = 8;
//const End_Type = 9;
//const Catalog_Number = 10;
//const Process = 11;
//const Material_File = 12;
//const Dialog_Switch = 13;
const Prop_Calc_Method = 14;
//const End_Calc_Method = 15;
//const Life_Category = 16;
const Material_Index = 17;
const End_Type_Index = 18;
const Inactive_Coils = 19;
const Add_Coils_Solid = 20;
const Density = 21;
const Torsion_Modulus = 22;
const Hot_Factor_Kh = 23;
const PC_Tensile_Endur = 24;
const PC_Tensile_Stat = 25;
//const unused = 26;
//const tbase010 = 27; // Hidden
//const tbase400 = 28; // Hidden
const const_term = 29; // Hidden
const slope_term = 30; // Hidden
const tensile_010 = 31; // Hidden

// Dependent Variables
const Mean_Dia = 0;
const Coils_A = 1;
const Rate = 2;
const Deflect_1 = 3;
const Deflect_2 = 4;
const L_1 = 5;
const L_2 = 6;
const L_Stroke = 7;
const L_Solid = 8;
const Slenderness = 9;
const ID_Free = 10;
const Weight = 11;
const Spring_Index = 12;
const Force_Solid = 13;
const Stress_1 = 14;
const Stress_2 = 15;
const Stress_Solid = 16;
const FactorSafety_2 = 17;
const FactorSafety_Solid = 18;
const FS_CycleLife = 19;
const Cycle_Life = 20;
const PC_Avail_Deflect = 21;
const Tensile = 22;
const Stress_Lim_Endur = 23;
const Stress_Lim_Stat = 24;
