import { CONSTRAINED, EQUATIONSET } from '../../store/actionTypes';
export const initialState = {
    "design_parameters": [
        {
            "name": "PRESSURE",
            "value": 500,
            "units": "LB/SQ-IN",
            "lmin": EQUATIONSET,
            "lmax": EQUATIONSET|CONSTRAINED,
            "cmin": 0,
            "cmax": 1500,
            "ioclass": 0,
            "sdlim": 0,
            "tooltip": "Gas PRESSURE applied to piston AREA"
        },
        {
            "name": "RADIUS",
            "value": 0.4,
            "units": "INCH",
            "lmin": EQUATIONSET|CONSTRAINED,
            "lmax": EQUATIONSET|CONSTRAINED,
            "cmin": 0,
            "cmax": 0.5,
            "ioclass": 0,
            "sdlim": 0,
            "tooltip": "Piston dimension; creates AREA where PRESSURE is applied"
        },
        {
            "name": "THICKNESS",
            "value": 0.04,
            "units": "INCH",
            "lmin": EQUATIONSET|CONSTRAINED,
            "lmax": EQUATIONSET|CONSTRAINED,
            "cmin": 0,
            "cmax": 0.05,
            "ioclass": 0,
            "sdlim": 0,
            "tooltip": "Dimension of cylinder wall providing containment for PRESSURE"
        }
    ],
    "state_variables": [
        {
            "name": "FORCE",
            "value": 0,
            "units": "LBS.",
            "lmin": EQUATIONSET|CONSTRAINED,
            "lmax": EQUATIONSET,
            "cmin": 1000,
            "cmax": 0,
            "ioclass": 0,
            "sdlim": 0,
            "tooltip": "Push generated by PRESSURE acting on piston AREA"
        },
        {
            "name": "AREA",
            "value": 0,
            "units": "SQ.-IN.",
            "lmin": EQUATIONSET,
            "lmax": EQUATIONSET,
            "cmin": 0,
            "cmax": 0,
            "ioclass": 0,
            "sdlim": 0,
            "tooltip": "Effective amount of piston surface exposed to PRESSURE"
        },
        {
            "name": "STRESS",
            "value": 0,
            "units": "PSI",
            "lmin": EQUATIONSET,
            "lmax": EQUATIONSET|CONSTRAINED,
            "cmin": 0,
            "cmax": 3000,
            "ioclass": 0,
            "sdlim": 0,
            "tooltip": "Force per unit area within cylinder wall; created by PRESSURE"
        }
    ],
    "labels": [
        {
            "name": "COMMENT",
            "value": "PCYL Default startup file ..."
        }
    ],
    "name": "initialState",
    "type": "Piston-Cylinder",
    "version": "1",
    "result": {
        "objective_value": 0,
        "termination_condition": "",
        "violated_constraint_count": 0
    }
};
