export const initialState = {
        "constants": [
            {
                "name": "Density",
                "value": 0.036,
                "units": "lb/cu-in"
            }
        ],
        "design_parameters": [
            {
                "name": "Length",
                "value": 12.0,
                "oldvalue": 1.0,
                "units": "inches",
                "lmin": 1,
                "lmax": 0,
                "cmin": 0,
                "cmax": 1.00,
                "ioclass": 0,
                "sdlim": 0,
                "smin": 1.0,
                "smax": 1.0,
                "vmin": -1.0,
                "vmax": -1.0
            },
            {
                "name": "Width",
                "value": 8.0,
                "oldvalue": 1.0,
                "units": "inches",
                "lmin": 1,
                "lmax": 0,
                "cmin": 0.0,
                "cmax": 1.0,
                "ioclass": 0,
                "sdlim": 0,
                "smin": 1.0,
                "smax": 1.0,
                "vmin": -1.0,
                "vmax": -1.0
            },
            {
                "name": "Height",
                "value": 8.0,
                "oldvalue": 1.0,
                "units": "inches",
                "lmin": 1,
                "lmax": 0,
                "cmin": 0.0,
                "cmax": 1.0,
                "ioclass": 0,
                "sdlim": 0,
                "smin": 1.0,
                "smax": 1.0,
                "vmin": -1.0,
                "vmax": -1.0
            }
        ],
        "state_variables": [
            {
                "name": "Volume",
                "value": 10.0,
                "oldvalue": 1.0,
                "units": "cu-in",
                "lmin": 0,
                "lmax": 0,
                "cmin": 1.0,
                "cmax": 2.0,
                "ioclass": 0,
                "sdlim": 0,
                "smin": 1.0,
                "smax": 1.0,
                "vmin": -1.0,
                "vmax": -1.0
            },
            {
                "name": "Surface Area",
                "value": 10.0,
                "oldvalue": 1.0,
                "units": "sq-in",
                "lmin": 0,
                "lmax": 0,
                "cmin": 0,
                "cmax": 0,
                "ioclass": 0,
                "sdlim": 0,
                "smin": 1.0,
                "smax": 1.0,
                "vmin": -1.0,
                "vmax": -1.0
            },
            {
                "name": "VolToSurfArea",
                "value": 10.0,
                "oldvalue": 1.0,
                "units": "ratio",
                "lmin": 0,
                "lmax": 0,
                "cmin": 0,
                "cmax": 1000,
                "ioclass": 0,
                "sdlim": 0,
                "smin": 1.0,
                "smax": 1.0,
                "vmin": -1.0,
                "vmax": -1.0
            },
            {
                "name": "Girth",
                "value": 10.0,
                "oldvalue": 1.0,
                "units": "sq-in",
                "lmin": 0,
                "lmax": 0,
                "cmin": 0,
                "cmax": 0,
                "ioclass": 0,
                "sdlim": 0,
                "smin": 1.0,
                "smax": 1.0,
                "vmin": -1.0,
                "vmax": -1.0 
            },
            {
                "name": "Length+Girth",
                "value": 10.0,
                "oldvalue": 1.0,
                "units": "sq-in",
                "lmin": 0,
                "lmax": 1,
                "cmin": 0,
                "cmax": 108.0,
                "ioclass": 0,
                "sdlim": 0,
                "smin": 1.0,
                "smax": 108.0,
                "vmin": -1.0,
                "vmax": -1.0
            },
            {
                "name": "Diagonal",
                "value": 10.0,
                "oldvalue": 1.0,
                "units": "sq-in",
                "lmin": 0,
                "lmax": 0,
                "cmin": 0,
                "cmax": 0,
                "ioclass": 0,
                "sdlim": 0,
                "smin": 1.0,
                "smax": 1.0,
                "vmin": -1.0,
                "vmax": -1.0
            },
            {
                "name": "Weight",
                "value": 10.0,
                "oldvalue": 1.0,
                "units": "sq-in",
                "lmin": 0,
                "lmax": 0,
                "cmin": 0,
                "cmax": 0,
                "ioclass": 0,
                "sdlim": 0,
                "smin": 1.0,
                "smax": 1.0,
                "vmin": -1.0,
                "vmax": -1.0
            }
        ],
        "labels": [
            {
                "name": "COMMENT",
                "value": "Rectangular Solid default startup file ..."
            }
        ],
        "name": "initialState",
        "type": "Solid",
        "version": "1",
        "result": {
            "objective_value": 0.0,
            "termination_condition": "None",
            "violated_constraint_count": 0
        },
        "system_controls": {
            "ioopt": 3,
            "maxit": 100,
            "weapon": 1,
            "nmerit": 1,
            "fix_wt": 1.5,
            "con_wt": 1.0,
            "zero_wt": 10.0,
            "viol_wt": 1.0,
            "mfn_wt": 0.01,
            "objmin": 0.00005,
            "del": 1.0,
            "delmin": 0.0001,
            "tol": 0.0001,
            "smallnum": 1.0e-07
        }
    };
