export const STARTUP = 'STARTUP';
export const LOAD = 'LOAD';
export const LOAD_INITIAL_STATE = 'LOAD_INITIAL_STATE';
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_USER = 'CHANGE_USER';

export const CHANGE_SYMBOL_VALUE = 'CHANGE_SYMBOL_VALUE';
export const FIX_SYMBOL_VALUE = 'FIX_SYMBOL_VALUE';
export const FREE_SYMBOL_VALUE = 'FREE_SYMBOL_VALUE';
export const CHANGE_SYMBOL_VIOLATION = 'CHANGE_SYMBOL_VIOLATION';
export const CHANGE_SYMBOL_CONSTRAINT = 'CHANGE_SYMBOL_CONSTRAINT';
export const CHANGE_SYMBOL_CONSTRAINTS = 'CHANGE_SYMBOL_CONSTRAINTS';
export const SET_SYMBOL_FLAG = 'SET_SYMBOL_FLAG';
export const RESET_SYMBOL_FLAG = 'RESET_SYMBOL_FLAG';
export const CHANGE_SYMBOL_INPUT = 'CHANGE_SYMBOL_INPUT';
export const CHANGE_SYMBOL_HIDDEN = 'CHANGE_SYMBOL_HIDDEN';

export const CHANGE_INPUT_SYMBOL_VALUES = 'CHANGE_INPUT_SYMBOL_VALUES';
export const SAVE_INPUT_SYMBOL_VALUES = 'SAVE_INPUT_SYMBOL_VALUES';
export const RESTORE_INPUT_SYMBOL_VALUES = 'RESTORE_INPUT_SYMBOL_VALUES';

export const CHANGE_OUTPUT_SYMBOL_VALUES = 'CHANGE_OUTPUT_SYMBOL_VALUES';
export const SAVE_OUTPUT_SYMBOL_CONSTRAINTS = 'SAVE_OUTPUT_SYMBOL_CONSTRAINTS';
export const RESTORE_OUTPUT_SYMBOL_CONSTRAINTS = 'RESTORE_OUTPUT_SYMBOL_CONSTRAINTS';

export const CHANGE_RESULT_OBJECTIVE_VALUE = 'CHANGE_RESULT_OBJECTIVE_VALUE';
export const CHANGE_RESULT_TERMINATION_CONDITION = 'CHANGE_RESULT_TERMINATION_CONDITION';
export const CHANGE_RESULT_VIOLATED_CONSTRAINT_COUNT = 'CHANGE_RESULT_VIOLATED_CONSTRAINT_COUNT';

export const CHANGE_LABELS_VALUE = 'CHANGE_LABELS_VALUE';
export const CHANGE_SYSTEM_CONTROLS_VALUE = 'CHANGE_SYSTEM_CONTROLS_VALUE';

export const SEARCH = 'SEARCH';
export const SEEK = 'SEEK';

export const AUTO_SAVE = 'AUTO_SAVE';

export const MIN = 'MIN';
export const MAX = 'MAX';

export const CONSTRAINED = 1;
export const FIXED = 2;
export const FDCL = 4;
