export const STARTUP = 'STARTUP';
export const LOAD = 'LOAD';
export const CHANGE_NAME = 'CHANGE_NAME';

export const CHANGE_DESIGN_PARAMETER_VALUE = 'CHANGE_DESIGN_PARAMETER_VALUE';
export const CHANGE_DESIGN_PARAMETER_VALUES = 'CHANGE_DESIGN_PARAMETER_VALUES';
export const SAVE_DESIGN_PARAMETER_VALUES = 'SAVE_DESIGN_PARAMETER_VALUES';
export const RESTORE_DESIGN_PARAMETER_VALUES = 'RESTORE_DESIGN_PARAMETER_VALUES';
export const CHANGE_DESIGN_PARAMETER_VIOLATION = 'CHANGE_DESIGN_PARAMETER_VIOLATION';
export const CHANGE_DESIGN_PARAMETER_CONSTRAINT = 'CHANGE_DESIGN_PARAMETER_CONSTRAINT';
export const SET_DESIGN_PARAMETER_FLAG = 'SET_DESIGN_PARAMETER_FLAG';
export const RESET_DESIGN_PARAMETER_FLAG = 'RESET_DESIGN_PARAMETER_FLAG';

export const CHANGE_STATE_VARIABLE_VALUE = 'CHANGE_STATE_VARIABLE_VALUE';
export const CHANGE_STATE_VARIABLE_VALUES = 'CHANGE_STATE_VARIABLE_VALUES';
export const CHANGE_STATE_VARIABLE_VIOLATION = 'CHANGE_STATE_VARIABLE_VIOLATION';
export const CHANGE_STATE_VARIABLE_CONSTRAINT = 'CHANGE_STATE_VARIABLE_CONSTRAINT';
export const SAVE_STATE_VARIABLE_CONSTRAINTS = 'SAVE_STATE_VARIABLE_CONSTRAINTS';
export const RESTORE_STATE_VARIABLE_CONSTRAINTS = 'RESTORE_STATE_VARIABLE_CONSTRAINTS';
export const SET_STATE_VARIABLE_FLAG = 'SET_STATE_VARIABLE_FLAG';
export const RESET_STATE_VARIABLE_FLAG = 'RESET_STATE_VARIABLE_FLAG';

export const CHANGE_RESULT_OBJECTIVE_VALUE = 'CHANGE_RESULT_OBJECTIVE_VALUE';
export const CHANGE_RESULT_TERMINATION_CONDITION = 'CHANGE_RESULT_TERMINATION_CONDITION';
export const CHANGE_RESULT_VIOLATED_CONSTRAINT_COUNT = 'CHANGE_RESULT_VIOLATED_CONSTRAINT_COUNT';

export const CHANGE_LABELS_VALUE = 'CHANGE_LABELS_VALUE';
export const CHANGE_SYSTEM_CONTROLS_VALUE = 'CHANGE_SYSTEM_CONTROLS_VALUE';

export const SEARCH = 'SEARCH';
export const SEEK = 'SEEK';
export const TRADE = 'TRADE';

export const MIN = 'MIN';
export const MAX = 'MAX';

export const CONSTRAINED = 1;
export const FIXED = 2;
