export const STARTUP = 'STARTUP';

export const CHANGE_DESIGN_PARAMETER_VALUE = 'CHANGE_DESIGN_PARAMETER_VALUE';
export const CHANGE_DESIGN_PARAMETER_VIOLATION = 'CHANGE_DESIGN_PARAMETER_VIOLATION';
export const CHANGE_DESIGN_PARAMETER_CONSTRAINT = 'CHANGE_DESIGN_PARAMETER_CONSTRAINT';
export const SET_DESIGN_PARAMETER_FLAG = 'SET_DESIGN_PARAMETER_FLAG';
export const RESET_DESIGN_PARAMETER_FLAG = 'RESET_DESIGN_PARAMETER_FLAG';

export const CHANGE_STATE_VARIABLE_VALUE = 'CHANGE_STATE_VARIABLE_VALUE';
export const CHANGE_STATE_VARIABLE_VIOLATION = 'CHANGE_STATE_VARIABLE_VIOLATION';
export const CHANGE_STATE_VARIABLE_CONSTRAINT = 'CHANGE_STATE_VARIABLE_CONSTRAINT';
export const SAVE_STATE_VARIABLE_CONSTRAINTS = 'SAVE_STATE_VARIABLE_CONSTRAINTS';
export const RESTORE_STATE_VARIABLE_CONSTRAINTS = 'RESTORE_STATE_VARIABLE_CONSTRAINTS';
export const SET_STATE_VARIABLE_FLAG = 'SET_STATE_VARIABLE_FLAG';
export const RESET_STATE_VARIABLE_FLAG = 'RESET_STATE_VARIABLE_FLAG';

export const CHANGE_SEARCH_RESULTS_OBJECTIVE_VALUE = 'CHANGE_SEARCH_RESULTS_OBJECTIVE_VALUE';
export const CHANGE_SEARCH_RESULTS_TERMINATION_CONDITION = 'CHANGE_SEARCH_RESULTS_TERMINATION_CONDITION';
export const CHANGE_SEARCH_RESULTS_FEASIBILITY = 'CHANGE_SEARCH_RESULTS_FEASIBILITY';

export const MIN = 'MIN';
export const MAX = 'MAX';
