export const NOOP = 'NOOP';
export const CHANGE_DESIGN_PARAMETER = 'CHANGE_DESIGN_PARAMETER';
export const CHANGE_DESIGN_PARAMETER_VIOLATION_MIN = 'CHANGE_DESIGN_PARAMETER_VIOLATION_MIN';
export const CHANGE_DESIGN_PARAMETER_VIOLATION_MAX = 'CHANGE_DESIGN_PARAMETER_VIOLATION_MAX';
export const CHANGE_STATE_VARIABLE = 'CHANGE_STATE_VARIABLE';
export const CHANGE_STATE_VARIABLE_VIOLATION_MIN = 'CHANGE_STATE_VARIABLE_VIOLATION_MIN';
export const CHANGE_STATE_VARIABLE_VIOLATION_MAX = 'CHANGE_STATE_VARIABLE_VIOLATION_MAX';
export const CHANGE_OBJECTIVE_VALUE = 'CHANGE_OBJECTIVE_VALUE';
