export const NOOP = 'NOOP';
export const CHANGE_DESIGN_PARAMETER = 'CHANGE_DESIGN_PARAMETER';
export const CHANGE_STATE_VARIABLE = 'CHANGE_STATE_VARIABLE';
export const CHANGE_OBJECTIVE_VALUE = 'CHANGE_OBJECTIVE_VALUE';
