#!/bin/bash
while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        echo "Master ref received.  Deploying master branch to production..."
        git --work-tree=/home/mikmil36/build/odop --git-dir=/home/mikmil36/git/odop checkout -f
        cd /home/mikmil36/build/odop
        ./scripts/build.sh
    else
        echo "Ref $ref successfully received.  Doing nothing: only the master branch may be deployed on this server."
    fi
done
